### ISSUE TITLE
Soundcloud support ?

### ISSUE THREAD

**Issue by IDerr** [dayxhep/discord-nodebot#1]
Hello, 

I was trying to play some music with your awesome bot, but you know sometimes, youtube is consuming a lot of bandwitdh .

Is it possible to support SoundCloud. 
It'll be awesome :)

**Comment by dayxhep** [comment]
SoundCloud support is in progress for the v3 :)

**Comment by IDerr** [comment]
Can you complete the project kanban with all the improvements in the V3 :)
